version: "3.9"

services: 
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Qwant
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: workouts
    volumes:
      - postrgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web: 
    build: .
    restart: always
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://Qwant:12345@db:5432/workouts
    volumes:
      - .:/code
    
volumes:
  postrgres_data:
